blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name ='blog'

urlpatterns =[path("",views.index,name="index"),
              path("post/<str:slug>",views.detail,name="detail"),
              path("contact",views.contact,name="contact"),
              path("about",views.about,name="about"),
              path("register",views.register,name="register"),
              path("login",views.login,name="login"),
              path("dashboard",views.dashboard,name="dashboard"),  
              path("logout",views.logout,name="logout"),
              path("forgotpassword",views.forgot_password,name="forgotpassword"),
              path("resetpassword/<uidb64>/<token>",views.reset_password,name="resetpassword"),
              path("newpost",views.new_post,name="newpost"),
              path("editpost/<int:post_id>",views.edit_post,name="editpost"),
              path("deletepost/<int:post_id>",views.delete_post,name="deletepost"),
              path("publishpost/<int:post_id>",views.publish_post,name="publishpost"),
              ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404='mysite.views.custom_page_not_found'

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User


# Category
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.ImageField(null=True, upload_to="posts/images")
    created_at = models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_published=models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self) :
         return self.title
    # slug = models.SlugField(unique=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # is_published = models.BooleanField(default=False)

    @property
    def formated_img_url(self):
        url=self.img_url if self.img_url.__str__().startswith(("http://","https://")) else self.img_url.url
        return url



class About_user(models.Model):
    content = models.TextField()

class Contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    message=models.TextField()
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name
    

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from blog.models import Category, Contact, Post

class ContactForm(forms.ModelForm):
    name=forms.CharField(label="Name",max_length=100,required=True)
    email=forms.EmailField(label="Email",required=True)
    message=forms.CharField(label="Message",required=True)

    class Meta:
        model= Contact
        fields=['name','email','message']

    def save(self, commit):
        feedback = super().save(commit)
        if commit:
            feedback.save()
        return feedback

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='username', max_length=100, required=True)
    email = forms.EmailField(label='email', max_length=100, required=True)
    password = forms.CharField(label='password', max_length=100, min_length=8, required=True)
    password_confirm = forms.CharField(label='password confirm', max_length=100, min_length=8, required=True)

    class Meta:
        model=User
        fields=['username','email','password']
    
    def clean(self):
        cleaned_data=super().clean()
        password=cleaned_data.get('password')
        password_confirm=cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords do not match")
        
class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100, required=True)
    password = forms.CharField(label='password', max_length=100, required=True)

    def clean(self):
        cleaned_data=super().clean()
        username=cleaned_data.get('username')
        password=cleaned_data.get('password')
        if username and password:
            user=authenticate(username=username,password=password)
            if user is None:
                raise forms.ValidationError("Invalid username or password")
            
class ForgotPasswordForm(forms.Form):
    email=forms.EmailField(label="email",required=True)

    def clean_email(self):
        email=self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email does not exist")
        return email
        
class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(label='New Password', min_length=8)
    confirm_password = forms.CharField(label='Confirm Password', min_length=8)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        #return cleaned_data
        
class NewPostForm(forms.ModelForm):
    title = forms.CharField(label='Title', max_length=100, required=True)
    content = forms.CharField(label='Content', required=True)
    category = forms.ModelChoiceField(label="Category",queryset=Category.objects.all(), required=True)
    img_url = forms.ImageField(label='Image', required=False)

    class Meta:
        model=Post
        fields=['title', 'content', 'category','img_url']
    
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')


        #custom validation
        if title and len(title) < 3:
            raise forms.ValidationError('Title must be at least 5 Characters long.')
        
        if content and len(content) < 100:
            raise forms.ValidationError('Content must be at least 10 Characters long.')
        
    def save(self, commit):
        post = super().save(commit)
        cleaned_data = super().clean()
        
        if cleaned_data.get('img_url'):
            img_url = cleaned_data.get('img_url')
        else:
            img_url="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/600px-No_image_available.svg.png"
        post.img_url = img_url
        if commit:
            post.save()
        return post

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
import logging
from blog.models import Post,Category,About_user
from django.http import Http404
from django.core.paginator import Paginator
from .forms import ForgotPasswordForm, LoginForm, ContactForm, NewPostForm,RegisterForm, ResetPasswordForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group

def index(request):
    all_post= Post.objects.filter(is_published=True)
    paginator= Paginator(all_post,24)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title= "latest posts"
    return render(request,"blog/index.html",{"title":title,"page_obj":page_obj})
     
def detail(request,slug):
    if not request.user.is_authenticated:
        messages.error(request, 'You are not logged in. Please log in to view the post.')
        return redirect('blog:login')
    if not request.user.has_perm('blog.view_post'):
        messages.error(request, 'You have no permission to view any posts')
        return redirect('blog:index')
    try:
        post= Post.objects.get(slug=slug)
        related_posts=Post.objects.filter(category=post.category).exclude(pk=post.id)
        title= post.title
    except Post.DoesNotExist:
        raise Http404("Post not found")
    return render(request,"blog/detail.html",{"post":post,"related_posts":related_posts,"title":title})

def contact(request):
    title= "Contact"
    form=ContactForm()
    if request.method=="POST":
        form=ContactForm(request.POST)
        if form.is_valid():
            feedback=form.save(commit=False)
            feedback.user=request.user
            feedback.save()
            messages.success(request,"Feedback saved successfully")
            return redirect('blog:contact')
    return render(request,"blog/contact.html",{"title":title, "form":form})

def about(request):
    title= "About"
    about_user_content=About_user.objects.first()
    if not about_user_content:
        about_user_content="Welcome to blog – a space where ideas, insights, and inspiration come to life!At blog, we are passionate about sharing valuable content on your blogs niche, e.g., technology, health, personal growth, social impact]. Our goal is to provide well-researched, engaging, and thought-provoking articles that add value to your daily life."
    else:
        about_user_content=about_user_content.content
    return render(request,"blog/about.html",{"about_user_content":about_user_content,"title":title})

def register(request):
    title= "Register"
    form=RegisterForm()
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            readers_group=Group.objects.get_or_create(name="Readers")
            authors_group=Group.objects.get_or_create(name="Authors")
            editors_group=Group.objects.get_or_create(name="Editors")
            user.groups.add(readers_group[0])
            user.groups.add(authors_group[0])
            user.groups.add(editors_group[0])
            messages.success(request, "Registration Successful")
            return redirect('blog:login')
    return render(request,"blog/register.html",{"form":form,"title":title})

def login(request):
    title= "Login"
    form=LoginForm()
    if request.method=="POST":  
        form=LoginForm(request.POST)
        print("Login successful")
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                print("Login successful")
                return redirect('blog:dashboard')
    return render(request,"blog/login.html",{"title":title,"form":form}) 

def dashboard(request):
    title= "Dashboard"
    blog_title= "Your Posts"
    all_posts=Post.objects.filter(user=request.user)
    paginator= Paginator(all_posts,9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,"blog/dashboard.html",{"title":title,"blog_title":blog_title,"page_obj":page_obj})

def logout(request):
    auth_logout(request)
    return redirect('blog:index')


def forgot_password(request):
    title= "Forgot Password"
    form = ForgotPasswordForm()
    logger= logging.getLogger('TestForgotPassword')
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            print(email)
            user = User.objects.get(email=email)
            token = default_token_generator.make_token(user)
            logger.info(f"Generated Token: {token}, User: {user}, Token: {token}")
            print("Generated Token:", token)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            current_site = get_current_site(request)
            domain = current_site.domain
            subject = "Reset Password Requested"
            message = render_to_string('blog/reset_password_email.html', {
                'domain': domain,
                'uid': uid,
                'token': token
            })

            send_mail(subject, message, 'noreply@gmail.com', [email])
            messages.success(request, 'Email has been sent')


    return render(request,'blog/forgot_password.html', {'title':title,'form': form})
 
def reset_password(request, uidb64, token):
    title= "Reset Password"
    form = ResetPasswordForm()
    if request.method == 'POST':
        #form
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            print(new_password)
            try:
                uid = urlsafe_base64_decode(uidb64)
                user = User.objects.get(pk=uid)
            except(TypeError, ValueError, OverflowError, User.DoesNotExist):
                user = None

            if user is not None and default_token_generator.check_token(user, token):
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Your password has been reset successfully!')
                return redirect('blog:login')
            else :
                messages.error(request,'The password reset link is invalid')
        else:
            print('not valid')
    return render(request,'blog/reset_password.html', {'form': form,'title':title})


@login_required
@permission_required('blog.add_post', raise_exception=True)
def new_post(request):
    title= "New Post"
    form=NewPostForm()
    categories=Category.objects.all()
    if request.method=="POST":
        form=NewPostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
            messages.success(request, "Post created successfully")
            return redirect('blog:dashboard')
    return render(request,"blog/new_post.html",{"title":title,"categories":categories,"form":form})

@login_required
@permission_required('blog.change_post', raise_exception=True)
def edit_post(request,post_id):
    title= "Edit Post"
    form=NewPostForm()
    categories=Category.objects.all()
    post=get_object_or_404(Post,id=post_id)
    if request.method=="POST":
        form=NewPostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post.save()
            messages.success(request, "Post updated successfully")
            return redirect('blog:dashboard')
    return render(request,"blog/edit_post.html",{"categories":categories,"title":title,"post":post,"form":form})

@login_required
@permission_required('blog.delete_post', raise_exception=True)
def delete_post(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    post.delete()
    messages.success(request, "Post deleted successfully")
    return redirect('blog:dashboard')

@login_required
@permission_required('blog.can_publish', raise_exception=True)
def publish_post(request,post_id):
    post=get_object_or_404(Post,id=post_id)
    post.is_published=True
    post.save()
    messages.success(request, "Post published successfully")
    return redirect('blog:dashboard')

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="d-flex gap-5 justify-content-center align-items-center m-5 p-3 rounded shadow">
        <img class="img-fluid rounded" style="height:300px; width:400px;" src="/media/posts/images/about_us.png" alt="">
        <div class="content">
            <h3 class="text-decoration-underline">About Us</h3>
            {{about_user_content}}
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title |truncatewords:6}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    {%include 'blog/include/header.html' %}
    {%block content%}
    {%endblock%}
    {%include 'blog/include/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-7">
            <h3>Welcome, {{ user.username }}!</h3>
            <h3>Here's a quick overview of your blog activities.</h3>
        </div>
        <div class="col d-flex justify-content-end">
            <div>
                <h2 class="text-decoration-underline">Your Groups:</h2>
                <ul>
                    {% for group in user.groups.all %}
                        <li>{{ group.name }}</li>
                    {% empty %}
                        <li>You are not a member of any groups.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-6">
            {% include 'blog/include/error.html' %}
        </div>
    </div>

    <div class="row">
        <h2 class="mt-3 text-decoration-underline">{{ blog_title }}</h2>
    </div>

    <div class="row m-3">
        {% if page_obj %}
            {% for post in page_obj %}
            <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body d-flex flex-column">
                        <!-- Side-by-side layout -->
                        <div class="row flex-grow-1 d-flex flex-column flex-md-row align-items-center">
                            <!-- Image Section -->
                            <div class="col-md-6 d-flex justify-content-center overflow-hidden" 
                                 style="height:200px; width:214;">
                                <img src="{{ post.formated_img_url }}" 
                                     class="img-fluid w-100 h-100 object-fit-cover rounded" 
                                     alt="...">
                            </div>
                            <!-- Content Section -->
                            <div class="col-md-6 d-flex flex-column h-100 p-2">
                                <h5 class="card-title">{{ post.title|truncatechars:30 }}</h5>
                                <p class="card-text">{{ post.content|truncatechars:100 }}</p>
                                <div class="mt-auto d-flex justify-content-between">
                                    <a href="{% url "blog:detail" slug=post.slug %}">Read More</a>
                                    <div class="text-decoration-none text-dark fw-bold">{{ post.category }}</div>
                                </div>
                            </div>
                        </div>
                        <!-- Buttons Section -->
                        <div class="row flex-grow-1">
                            <div class="mt-auto d-flex justify-content-evenly mt-2 button-container">
                                <a class="btn btn-warning btn-md mt-2 px-4" 
                                   href="{% url "blog:editpost" post_id=post.id %}">Edit</a>
                                <button class="btn btn-danger btn-md mt-2" 
                                        onclick="ConfirmBeforeDelete(`{% url 'blog:deletepost' post_id=post.id %}`)">Delete</button>
                                {% if not post.is_published and perms.blog.can_publish %}
                                    <button class="btn btn-success btn-md mt-2" 
                                            onclick="ConfirmBeforePublish(`{% url 'blog:publishpost' post_id=post.id %}`)">Publish Post</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <div class="col-12">
            <h3>No posts found.</h3>
        </div>
        {% endif %}
    </div>

    <div class="row">
        {% if perms.blog.add_post %}
        <div class="d-flex justify-content-center button-container">
            <a href="{% url "blog:newpost" %}" class="btn btn-success">Add Post</a>
        </div>
        {% endif %}
    </div>

    <div class="col-12 my-5">
        {% if page_obj.has_other_pages %}
        <nav style="margin-bottom:5px;" aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo; first</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">previous</span>
                    </a>
                </li>
                {% endif %}
                <li class="page-item">
                    <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">next</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">last &raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
<script>
    function ConfirmBeforeDelete(url) {
        if (confirm("Are you sure you want to delete this post?")) {
            window.location.href = url;
        }
    }
    function ConfirmBeforePublish(url) {
        if (confirm("Are you sure you want to publish this post?")) {
            window.location.href = url;
        }
    }
</script>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html'%}
{%block content%}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4 text-decoration-underline">{{post.title}}</h1>
              <p class="text-muted">{{post.created_at|date:"F j, Y"}}</p>
              <img style="height:300px; width:533px; object-fit: cover;" src="{{post.formated_img_url}}" class="img-fluid mb-4" alt="Blog Image">
              </div>
            {%if related_posts%}
              <div class="col-lg-4">
                <div style="margin-top:90px;" class="card rounded shadow">
                  <div class="card-body">
                    <h5 class="card-title text-decoration-underline">Related Posts</h5>
                    <ul class="list-unstyled">
                      {%for related_post in related_posts%}
                      <li><a href="{% url 'blog:detail' slug=related_post.slug%}">{{related_post.title}}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            {% endif %}
            <div class="col-lg-12 mb-5 ">
              <p>{{post.content}}</p>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid ">
    <div class="row my-2">
        <div class="col">
            <h2 >{{blog_title}}</h2>
        </div>
    </div>
    <div class="row m-3">
        {% if page_obj %}
        {% for post in page_obj %}
        <div class="col-12 col-sm-12 col-lg-4 mb-4">
            <div class="card h-100 shadow">
                <div class="card-body d-flex flex-column">
                    <!-- Side-by-side layout -->
                    <div class="row flex-grow-1 d-flex flex-column flex-md-row align-items-center">
                        <!-- Image Section -->
                        <div class="col-md-6 d-flex justify-content-center overflow-hidden" style="height:200px; width:214;">
                            <img src="{{ post.formated_img_url }}" class="img-fluid w-100 h-100 object-fit-cover rounded" alt="...">
                        </div>
                        <!-- Content Section -->
                        <div class="col-md-6 d-flex flex-column h-100 p-2">
                            <h5 class="card-title">{{ post.title|truncatechars:30 }}</h5>
                            <p class="card-text">{{ post.content|truncatechars:100 }}</p>
                            <div class="mt-auto d-flex justify-content-between">
                                <a href="{% url "blog:detail" slug=post.slug %}">Read More</a>
                                <div class="text-decoration-none text-dark fw-bold">{{ post.category }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <div class="col-12">
        <h3>No posts found.</h3>
    </div>
    {% endif %}
        <div class="col-12 my-4">
            {%if page_obj.has_other_pages%}
            <nav style="margin-bottom:5px;" aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {%if page_obj.has_previous%}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo; first</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">previous</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                    {%if page_obj.has_next%}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                            <span aria-hidden="true">last &raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
    <div class="row">
        
    </div>
    
</div>

{%endblock%}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4 p-5 rounded shadow">
                <h3 class="text-decoration-underline">Login</h3>
                <div class="">
                    <div class="col-12">
                        <span class="fw-bold"></span>
                        <span class="text-danger"></span>
                    </div>
                </div>
    
                <div class="col-12">
                    <span class="text-danger"></span>
                </div>
                {%include 'blog/include/error.html'%}

                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:""}}">
                        </div>
                        {%if form.username.errors%}
                        <div class="col-12">
                            <p class="text-danger">{{ form.username.errors.0 }}</p>
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        {%if form.password.errors%}
                        <div class="col-12">
                            <p class="text-danger">{{ form.password.errors.0 }}</p>
                        </div>
                        {% endif %}
                        <div class="my-3 d-flex justify-content-end">
                             <div class="col-6">
                            <a href={%url "blog:forgotpassword"%}>Forgot Password</a>
                            </div>
                            <div class="col-6  d-flex justify-content-end button-container">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/reset_password_email.html
{% autoescape off %}
Hello,

You requested a password reset for your account at {{ domain }}.

Please click the link below to reset your password:

http://{{ domain }}{% url 'blog:resetpassword'   uidb64=uid token=token %}

Thank you!
{% endautoescape %}